development: &default
  adapter: postgresql
  encoding: unicode
  database: bettrchat_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: bettrchat_test
  min_messages: warning
